### ISSUE TITLE
auto-negotiation bit definition wrong

### ISSUE THREAD

**Issue by exelsior87** [STMicroelectronics/stm32-dp83848#1]
https://github.com/STMicroelectronics/stm32-dp83848/blob/21b1c9f717739aa7a27558cb757c8cacd99622b4/dp83848.h#L312

According to the DP83848 datasheet, the Auto-Negotiation complete bit is 0x10 but it defined as 0x100 in the code.
I think DP83848_PHYSCSR_AUTONEGO_DONE ((uint16_t)0x100U) defined value should be 0x10.

datasheet url : https://www.alldatasheet.com/view.jsp?Searchword=DP83848

**Comment by HBOSTM** [comment]
Hello @exelsior87,

Could you please share the document and the page showing where to find this information?

Best Regards,

**Comment by exelsior87** [comment]
[DP83848CVV.PDF](https://github.com/STMicroelectronics/stm32-dp83848/files/11495337/DP83848CVV.PDF)

please, refer to the attatchment.
On page 39, there are two AutoNegoComplete definitions in 'Basic Mode Status Register' and 'PHY Status Register'.
0x20 in Basic Mode Status Register and 0x10 in PHY Status Register.

https://github.com/STMicroelectronics/stm32-dp83848/blob/21b1c9f717739aa7a27558cb757c8cacd99622b4/dp83848.h#L62

https://github.com/STMicroelectronics/stm32-dp83848/blob/21b1c9f717739aa7a27558cb757c8cacd99622b4/dp83848.c#LL358C71-L358C71

In DP83848_GetLinkState function, read register value from PHYSCSR (address 0x0010).
so, I think DP83848_PHYSCSR_AUTONEGO_DONE ((uint16_t)0x100U) defined value should be 0x10.

Alternatively, I think it should be modified as follows:

`
if(pObj->IO.ReadReg(pObj->DevAddr, DP83848_BSR, &readval) < 0) {
  return DP83848_STATUS_READ_ERROR;
}

if((readval & DP83848_BSR_AUTONEGO_CPLT) == 0) {
  return DP83848_STATUS_AUTONEGO_NOTDONE;
}`

**Comment by HBOSTM** [comment]
Hello @exelsior87 ,

Firstly, thank you for this contribution. DP83848_PHYSCSR_AUTONEGO_DONE is a mask used to check if auto-negotiation is done.
Restart Auto-Negotiation is bit number nine for this equal to 0x100U.
So, please allow me to close this issue and thank you again.

Best Regards,
Houssine

**Comment by exelsior87** [comment]
DP83848_PHYSCSR_AUTONEGO_DONE is a mask used to check if auto-negotiation is done.

yes, you're right.
but, which register??

https://github.com/STMicroelectronics/stm32-dp83848/blob/21b1c9f717739aa7a27558cb757c8cacd99622b4/dp83848.c#L358-L367

it reads from register DP83848_PHYSCSR (register address: 0x0010).
`#define DP83848_PHYSCSR  ((uint16_t)0x0010U)`

![physts](https://github.com/STMicroelectronics/stm32-dp83848/assets/39573903/112fd18a-eafd-4d93-865a-9b8a6d3d0b5b)

if DP83848_PHYSCSR_AUTONEGO_DONE is 0x100U, it check Page Receive.
want to use the value read from PHYSCSR, the mask set to be 0x10.

or

it should read from DP83848_BSR (register address: 0x01) with  DP83848_BSR_AUTONEGO_CPLT mask.
`#define DP83848_BSR      ((uint16_t)0x0001U)`

![bmsr](https://github.com/STMicroelectronics/stm32-dp83848/assets/39573903/61c4bb09-67c4-4baf-a318-28005afd3657)

`if(pObj->IO.ReadReg(pObj->DevAddr, DP83848_PHYSCSR, &readval) < 0) `
should to be
===> `if(pObj->IO.ReadReg(pObj->DevAddr, DP83848_BSR, &readval) < 0)`

and
`if((readval & DP83848_PHYSCSR_AUTONEGO_DONE) == 0)`
should to be
==> `if((readval & DP83848_BSR_AUTONEGO_CPLT) == 0)`

**Comment by HBOSTM** [comment]
ST Internal Reference: 157683
